### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: no such element:

### ISSUE THREAD

**Issue by ddisaster** [Kagee/audible-downloader#10]
Hi,

I'm getting following error and my system is Manjaro Linux. Looks like the Audible side has changed since last update of your tool. Or I'm rong?

Thanks for help and thanks for publishing your tool.

./download.py -l de
Username: xxxxx
Password: 
Configuring browser
Starting browser
Opening Audible for language de
Logging in to Amazon/Audible
Opening Audible library
Selecting books from 'All Time'
Traceback (most recent call last):
  File "./download.py", line 428, in <module>
    configure_audible_library(driver, lang)
  File "./download.py", line 288, in configure_audible_library
    select = Select(driver.find_element_by_id("adbl_time_filter"))
  File "/home/christoph/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/home/christoph/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/home/christoph/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/christoph/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"adbl_time_filter"}
  (Session info: chrome=67.0.3396.87)
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.14.52-1-MANJARO x86_64)

**Comment by stemnic** [comment]
I can confirm that the same error shows up on windows 10 with audible.com

> python download.py -w "C:\Users\User\Music\audible"
> Username: ***********************
> Password:
> Configuring browser
> Starting browser
> 
> DevTools listening on ws://127.0.0.1:5489/devtools/browser/cd5ed41a-7df8-46a4-aa79-a45d2dfab1e1
> Opening Audible for language us
> Logging in to Amazon/Audible
> Opening Audible library
> Selecting books from 'All Time'
> Traceback (most recent call last):
>   File "download.py", line 428, in <module>
>     configure_audible_library(driver, lang)
>   File "download.py", line 288, in configure_audible_library
>     select = Select(driver.find_element_by_id("adbl_time_filter"))
>   File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
>     return self.find_element(by=By.ID, value=id_)
>   File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
>     'value': value})['value']
>   File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"adbl_time_filter"}
>   (Session info: chrome=71.0.3578.98)
>   (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.17134 x86_64)

**Comment by ghost** [comment]
Same on Ubuntu 18.10 with Chrome

**Comment by vwade** [comment]
Same on OSX High Sierra 10.13.3
<img width="1195" alt="Screen Shot 2019-04-08 at 6 23 18 AM" src="https://user-images.githubusercontent.com/44330039/55727442-dc8aee80-59c6-11e9-8950-f89f316df9a3.png">
